### ISSUE TITLE
Could I use FUSION to analyze data of somatic mutation?

### ISSUE THREAD

**Issue by ggoodstudydaydayup** [opain/Calculating-FUSION-TWAS-weights-pipeline#1]
Hi,
    I have some data of somatic mutation, could I use FUSION to analyze the relationship between gene expression and somatic SNP ?
Best wishes,
Liu

**Comment by opain** [comment]
Sorry, I have only just seen this. This repo is just a wrapper for FUSION scripts. I recommend contacting the FUSION developers. https://github.com/gusevlab/fusion_twas
