### ISSUE TITLE
.pos file

### ISSUE THREAD

**Issue by alyssacl** [opain/Calculating-FUSION-TWAS-weights-pipeline#2]
Hello, I was wondering how you created your .pos file?
I was able to create my weights but no .pos file generated?
Thanks,
Alyssa

**Comment by opain** [comment]
Sorry I somehow missed this notification!

Did you see [step 3](https://github.com/opain/Calculating-FUSION-TWAS-weights-pipeline?tab=readme-ov-file#3-create-folder-containing-snp-weights-in-the-same-format-as-the-fusion-released-snp-weights) in the instructions?

The [OP_packaging_fusion_weights.R](https://github.com/opain/Calculating-FUSION-TWAS-weights-pipeline/blob/master/OP_packaging_fusion_weights.R) script creates the .pos file, and other files typically provided with FUSION format SNP-weights.
